baseURL = "https://andys.page/"
languageCode = "en-us"
author = "Andy Salerno"
title = "⌨️🤷🏻‍♂️📷"
theme = "hugo-tanka"
enableEmoji = true
hasCJKLanguage = false
pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Andy, xor Andrew"
  tagline = "Professional software developer / hobbyist street photographer"
  faviconfile = "images/favicon.png"
  highlightjs = false
  highlightjslanguages = ["rust"]
  progressively = false

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/andysalerno"
    weight = 3
[[menu.primary]]
    name = "Photo gallery"
    url = "/gallery/"
    weight = 4
[[menu.primary]]
    name = "Flickr"
    url = "https://www.flickr.com/photos/andysalerno/"
    weight = 5
[[menu.primary]]
    name = "Rss (there are dozens of us!)"
    url = "/index.xml"
    weight = 6